on:
  schedule:
    # every day at 10:00 am (Beijing time)
    - cron: '0 2 * * *'
    # every day at 5:00 pm (Beijing time)
    - cron: '0 9 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navi-language/setup-navi@v1
        with:
          navi-version: 0.9.0-nightly
      - name: Perform
        env:
          CI: 1
          BOOK_OPENID: ${{ secrets.BOOK_OPENID }}
          BOOK_ENDPOINT: ${{ secrets.BOOK_ENDPOINT }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          BOOK_TEL: ${{ secrets.BOOK_TEL }}
          BOOK_CARCODE: ${{ secrets.BOOK_CARCODE }}
          BOOK_CARCODE1: ${{ secrets.BOOK_CARCODE1 }}
          BOOK_TEL_B: ${{ secrets.BOOK_TEL_B }}
          BOOK_CARCODE_B: ${{ secrets.BOOK_CARCODE_B }}
          BOOK_CARCODE_B1: ${{ secrets.BOOK_CARCODE_B1 }}
        run: |
          navi run main.nv
