on:
  schedule:
    # every day at 10:00 (Beijing time)
    # - cron: '0 2 * * *'
    # every day at 14:00 (Beijing time)
    # - cron: '0 6 * * *'
    # every day at 16:56 (Beijing time)
    - cron: '56 8 * * *'
    # every day at 16:57 (Beijing time)
    - cron: '57 8 * * *'
    # every day at 16:58 (Beijing time)
    - cron: '58 8 * * *'
    # every day at 16:59 (Beijing time)
    - cron: '59 8 * * *'
    # every day at 17:00 (Beijing time)
    - cron: '0 9 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navi-language/setup-navi@v1
        with:
          navi-version: nightly
      - name: Perform
        env:
          CI: 1
          BOOK_OPENID: ${{ secrets.BOOK_OPENID }}
          BOOK_ENDPOINT: ${{ secrets.BOOK_ENDPOINT }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          BOOK_TEL: ${{ secrets.BOOK_TEL }}
          BOOK_CARCODE: ${{ secrets.BOOK_CARCODE }}
          BOOK_CARCODE1: ${{ secrets.BOOK_CARCODE1 }}
          BOOK_TEL_B: ${{ secrets.BOOK_TEL_B }}
          BOOK_CARCODE_B: ${{ secrets.BOOK_CARCODE_B }}
          BOOK_CARCODE_B1: ${{ secrets.BOOK_CARCODE_B1 }}
        run: |
          navi run main.nv
