on:
  schedule:
    # every day at 10:00 am
    - cron: '0 10 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Navi
        run: |
          curl -sSL https://navi-lang.org/install | sh -s -- v0.9.0-nightly
      - name: Run App
        env:
          CI: 1
        run: |
          navi run main.nv
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Navi
        run: |
          curl -sSL https://navi-lang.org/install | sh -s -- v0.9.0-nightly
      - name: Run Tests
        env:
          CI: 1
        run: |
          navi test
