on:
  push:
  schedule:
    # every day at 10:00 am
    - cron: '0 10 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navilang/setup-navi@v1
        with:
          navi-version: 0.9.0-nightly
      - name: Run App
        env:
          CI: 1
        run: |
          navi run main.nv
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navilang/setup-navi@v1
        with:
          navi-version: 0.9.0-nightly
      - name: Run Tests
        env:
          CI: 1
        run: |
          navi test
